apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    app: ace-prod-ecollection
  name: ace-prod-ecollection
  namespace: ace-mq
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ace-prod-ecollection
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ace-prod-ecollection
    spec:
      containers:
      - env:
        - name: LICENSE
          value: accept
        - name: MQ_QMGR_NAME
          value: LQM.IXC
        - name: MQSI_PERSISTENT_MONITORING_EVENTS
          value: "1"
        image: docker-registry/ibm-ace-gold-prod
        imagePullPolicy: Always
        name: ace-prod-ecollection
        ports:
        - containerPort: 7600
          protocol: TCP
        - containerPort: 1414
          protocol: TCP
        - containerPort: 7800
          protocol: TCP
        - containerPort: 7843
          protocol: TCP
        - containerPort: 9157
          protocol: TCP
        - containerPort: 9443
          protocol: TCP
        - containerPort: 9483
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /home/aceuser/build
          name: aceuser
        - mountPath: /home/aceuser/ace-server/log
          name: volume-1
        - mountPath: /home/aceuser/ace-server/run
          name: volume-2
        - mountPath: /home/aceuser/ace-server/overrides
          name: volume-3
        - mountPath: /home/aceuser/ace-server/shared-classes
          name: volume-4
        - mountPath: /mnt/mqm
          name: volume-5
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: aceuser
        persistentVolumeClaim:
          claimName: ace-dev-ace-ecollection-build-pvc
      - name: volume-1
        persistentVolumeClaim:
          claimName: ace-dev-ace-ecollection-logs-pvc
      - name: volume-2
        persistentVolumeClaim:
          claimName: ace-dev-ace-ecollection-run-pvc
      - name: volume-3
        persistentVolumeClaim:
          claimName: ace-dev-ace-ecollection-overrides-pvc
      - name: volume-4
        persistentVolumeClaim:
          claimName: ace-dev-ace-ecollection-shared-classes-pvc
      - name: volume-5
        persistentVolumeClaim:
          claimName: ace-dev-ace-ecollection-data-pvc-nfs
